channels:
  - conda-forge
name: py35
dependencies:
- openssl
- pip
- python=3.5.2
- readline
- setuptools
- sqlite
- wheel
- zlib
- pip:
  - Sphinx
  - graphviz
  - sphinx-autodoc-napoleon-typehints
  - hopcroftkarp
  - multiset